# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

db:
  type: postgresql:11
  disk: 1024
searchelastic:
  type: elasticsearch:7.2
  disk: 1024