name: app

type: "java:11"
disk: 1024

hooks:
    build: ./mvnw package -DskipTests -Dquarkus.package.uber-jar=true

relationships:
    mongodb: 'mongodb:mongodb'

web:
    commands:
        start: java -jar $JAVA_OPTS $CREDENTIAL -Dquarkus.http.port=$PORT target/panache-mongodb-1.0-SNAPSHOT-runner.jar
